language: node_js
cache:
directories:
- node_modules
notifications:
email: false
node_js:
- '7'
branches:
except:
- /^v\d+\.\d+\.\d+$/
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable